//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
//
// Patch Constant signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TessFactor            0   x           0  LINEDEN   float   x   
// SV_TessFactor            1   x           1  LINEDET   float   x   
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// CPOINT                   0   xyzw        0     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// CPOINT                   0   xyzw        0     NONE   float   xyzw
//
// Tessellation Domain   # of control points
// -------------------- --------------------
// Isoline                                 4
//
// Tessellation Output Primitive  Partitioning Type 
// ------------------------------ ------------------
// Line                           Integer           
//
hs_5_0
hs_decls 
dcl_input_control_point_count 4
dcl_output_control_point_count 4
dcl_tessellator_domain domain_isoline
dcl_tessellator_partitioning partitioning_integer
dcl_tessellator_output_primitive output_line
dcl_globalFlags refactoringAllowed | skipOptimization
hs_control_point_phase 
dcl_input vOutputControlPointID
dcl_input v[4][0].xyzw
dcl_output o0.xyzw
dcl_temps 1
mov r0.x, vOutputControlPointID
mov r0.xyzw, v[r0.x + 0][0].xyzw
mov o0.xyzw, r0.xyzw
ret 
hs_join_phase 
dcl_output_siv o0.x, finalLineDensityTessFactor
dcl_output_siv o1.x, finalLineDetailTessFactor
dcl_temps 1
mov r0.x, l(1.000000)
mov r0.y, l(8.000000)
mov o0.x, r0.x
mov o1.x, r0.y
ret 
// Approximately 9 instruction slots used
