//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
///
// Parameters:
//
//   bool LOOP_COUNT;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   LOOP_COUNT   b0       1
//

    vs_2_0
    def c0, 2, 1, 0.5, 0
    dcl_position v0
    mov r0, v0
    if b0
      mul r1, r0, c0.xyzy
    else
      mul r1, r0, c0.xyyy
    endif
    mov oPos, r1

// approximately 9 instruction slots used
