//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
///
// Parameters:
//
//   int LOOP_COUNT;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   LOOP_COUNT   i0       1
//

    vs_2_0
    def c0, 2, 0.5, 0, 0
    dcl_position v0
    mov r0.xy, v0.xzzw
    rep i0
      mul r0.xy, r0, c0
    endrep
    mov oPos.xz, r0.xyyw
    mov oPos.yw, v0

// approximately 9 instruction slots used
