//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
/    vs_2_0
    def c0, 5, 0, 0, 0
    dcl_position v0
    mov oPos, v0
    mov oPts, c0.x

// approximately 2 instruction slots used
