//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   float2 uvOrig;                     // Offset:    0 Size:     8
//   float4 _CenterRadius;              // Offset:   16 Size:    16
//   float _Angle;                      // Offset:   32 Size:     4
//   float4 _LightData[4];              // Offset:   48 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// $Globals                          cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer cb0[5], immediateIndexed
dcl_output o0.xyzw
dcl_temps 4
div r0.xy, cb0[0].xyxx, cb0[1].zwzz
dp2 r0.x, r0.xyxx, r0.xyxx
sqrt r0.x, r0.x
add r0.x, -r0.x, l(1.000000)
mov r0.yz, cb0[0].xxyx
mov r0.w, r0.x
mov r1.x, l(0)
loop 
  ige r1.y, r1.x, l(4)
  breakc_nz r1.y
  max r1.y, r0.w, l(0.000000)
  add r1.y, r1.y, cb0[4].x
  mul r1.y, r1.y, r1.y
  mul r0.w, r1.y, cb0[2].x
  sincos r2.x, r3.x, r0.w
  mov r2.y, r3.x
  add r0.yz, r0.yyzy, r2.xxyx
  iadd r1.x, r1.x, l(1)
endloop 
mad o0.xyzw, r0.yyyy, r0.zzzz, cb0[1].xyxy
ret 
// Approximately 21 instruction slots used
