//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// smpLinClamp                       sampler      NA          NA    0        1
// ITex0                             texture  float4          2d    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// inUV                     0   xy          0     NONE   float   xy  
// inCOLOR                  0   xyzw        1     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v0.xy
dcl_input_ps linear v1.xyzw
dcl_output o0.xyzw
dcl_temps 2
lt r0.xy, l(0.000000, 0.000000, 0.000000, 0.000000), v0.xyxx
not r0.zw, r0.xxxy
ieq r0.z, r0.z, r0.w
add r1.xy, v0.xxxx, l(7.000000, 12.000000, 0.000000, 0.000000)
movc r0.z, r0.z, r1.y, v0.x
movc r0.y, r0.y, v0.x, r1.x
movc r0.x, r0.x, r0.z, r0.y
mov r0.y, v0.y
sample r0.xyzw, r0.xyxx, t0.xyzw, s0
mul o0.xyzw, r0.xyzw, v1.xyzw
ret 
// Approximately 11 instruction slots used
