//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// T1D                               texture  float4          1d    0        1
// T2D                               texture  float4          2d    1        1
// T2DArray                          texture  float4     2darray    2        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_resource_texture1d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2darray (float,float,float,float) t2
dcl_output o0.xyzw
dcl_temps 1
resinfo r0.xyzw, l(0), t0.xyzw
ftou r0.x, r0.x
utof o0.x, r0.x
resinfo_uint r0.xyzw, l(0), t1.xyzw
utof o0.y, r0.y
resinfo_uint r0.xyzw, l(0), t2.xyzw
utof o0.z, r0.w
mov o0.w, l(1.000000)
ret 
// Approximately 9 instruction slots used
