//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyz 
// TEXCOORD                 0   x           1     NONE     int       
// TEXCOORD                 1   x           2     NONE     int       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// IntPos                   0   xyzw        1     NONE     int       
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_input v0.xyz
dcl_output_siv o0.xyzw, position
dcl_temps 1
lt r0.x, v0.y, v0.x
and o0.x, r0.x, v0.z
mov o0.yzw, l(0,0,0,0)
ret 
// Approximately 4 instruction slots used
