//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Buffer Definitions: 
//
// cbuffer RenderTargetParams
// {
//
//   int Width;                         // Offset:    0 Size:     4
//   int Height;                        // Offset:    4 Size:     4
//   float AspectRatio;                 // Offset:    8 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// RenderTargetParams                cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xy  
// NORMAL                   0   xyz         1     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[1], immediateIndexed
dcl_input v0.xy
dcl_output_siv o0.xyzw, position
dcl_temps 1
dp2 r0.x, v0.xyxx, v0.xyxx
min r0.x, r0.x, l(1.000000)
add o0.xy, -r0.xxxx, l(1.000000, 1.000000, 0.000000, 0.000000)
ishl r0.xy, cb0[0].xyxx, l(1, 1, 0, 0)
itof o0.zw, r0.xxxy
ret 
// Approximately 6 instruction slots used
