//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
// OFFSET                   0   x           2     NONE   float   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// RCPPOS                   0   xyzw        1     NONE   float   xyzw
// RCPTC                    0   xy          2     NONE   float   xy  
// RCPOFF                   0     z         2     NONE   float     z 
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_input v0.xyzw
dcl_input v1.xy
dcl_input v2.x
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_output o2.xy
dcl_output o2.z
mov o0.xyzw, v0.xyzw
rcp o1.xyzw, v0.xyzw
rcp o2.xy, v1.xyxx
rcp o2.z, v2.x
ret 
// Approximately 5 instruction slots used
