//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   float angle;                       // Offset:    0 Size:     4
//   float2 angle2;                     // Offset:    4 Size:     8
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// $Globals                          cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float    yz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// SIN                      2   xy          1     NONE   float   xy  
// COS                      2     zw        1     NONE   float     zw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[1], immediateIndexed
dcl_input v0.yz
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
dcl_output o1.zw
dcl_temps 2
add r0.x, cb0[0].x, cb0[0].x
sincos o0.x, null, r0.x
mov o0.y, v0.y
sincos r0.x, r1.x, cb0[0].x
add o0.z, r1.x, v0.z
mov o0.w, r0.x
sincos o1.xy, null, cb0[0].yzyy
sincos null, o1.zw, cb0[0].yyyz
ret 
// Approximately 9 instruction slots used
