//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T vs_5_0 /Fo sincos.o /Fc sincos.asm sincos
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   float angle;                       // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// $Globals                          cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyzw        0     NONE  float    yz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Position              0   xyzw        0      POS  float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[1], immediateIndexed
dcl_input v0.yz
dcl_output_siv o0.xyzw, position
dcl_temps 2
add r0.x, cb0[0].x, cb0[0].x
sincos o0.x, null, r0.x
mov o0.y, v0.y
sincos r0.x, r1.x, cb0[0].x
add o0.z, r1.x, v0.z
mov o0.w, r0.x
ret 
// Approximately 7 instruction slots used
