//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int AConstantInt;                  // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// $Globals                          cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float       
// TEXCOORD                 0   x           1     NONE     int   x   
// TEXCOORD                 1   x           2     NONE     int   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// IntPos                   0   xyzw        1     NONE     int   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[1], immediateIndexed
dcl_input v1.x
dcl_input v2.x
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_temps 1
dcl_indexableTemp x0[2], 4
dcl_indexableTemp x1[2], 4
mov x0[0].xy, l(0,0,0,0)
mov x0[1].xy, l(0,0,0,0)
mov x1[0].xy, l(0,0,0,0)
mov x1[1].xy, l(0,0,0,0)
mov r0.x, v1.x
mov x0[r0.x + 0].xy, l(1.000000,1.000000,0,0)
iadd r0.x, v1.x, l(1)
mov x0[r0.x + 0].xy, l(0,0,0,0)
mov r0.x, v2.x
mov x1[r0.x + 0].xy, cb0[0].xxxx
iadd r0.x, v2.x, l(2)
mov x1[r0.x + 0].xy, l(0,0,0,0)
and r0.x, v1.x, l(1)
mov r0.xy, x0[r0.x + 0].xyxx
mov o0.xyzw, r0.xxyy
and r0.x, v2.x, l(1)
mov r0.xy, x1[r0.x + 0].xyxx
mov o1.xyzw, r0.xxyy
ret 
// Approximately 19 instruction slots used
