//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T cs_5_0 /Fo BasicCompute11StructuredBufferDouble.o /Fc
//    BasicCompute11StructuredBufferDouble.asm /Op /ECSMain
//    /DUSE_STRUCTURED_BUFFERS /DTEST_DOUBLE BasicCompute11.hlsl
//
//
// Buffer Definitions: 
//
// Resource bind info for Buffer0
// {
//
//   struct BufType
//   {
//       
//       int i;                         // Offset:    0
//       float f;                       // Offset:    4
//       double d;                      // Offset:    8
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
// Resource bind info for Buffer1
// {
//
//   struct BufType
//   {
//       
//       int i;                         // Offset:    0
//       float f;                       // Offset:    4
//       double d;                      // Offset:    8
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
// Resource bind info for BufferOut
// {
//
//   struct BufType
//   {
//       
//       int i;                         // Offset:    0
//       float f;                       // Offset:    4
//       double d;                      // Offset:    8
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// Buffer0                           texture  struct         r/o    0        1
// Buffer1                           texture  struct         r/o    1        1
// BufferOut                             UAV  struct         r/w    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed | enableDoublePrecisionFloatOps
dcl_resource_structured t0, 16 
dcl_resource_structured t1, 16 
dcl_uav_structured u0, 16
dcl_input vThreadID.x
dcl_temps 3
dcl_thread_group 1, 1, 1
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r0.xyzw, vThreadID.x, l(0), t0.zwxy
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xyzw, vThreadID.x, l(0), t1.zwxy
dadd r2.zw, r0.xyxy, r1.xyxy
iadd r2.x, r0.z, r1.z
add r2.y, r0.w, r1.w
store_structured u0.xyzw, vThreadID.x, l(0), r2.xyzw
ret 
// Approximately 7 instruction slots used
