//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T cs_5_0 /Fo BasicCompute11.o /Fc BasicCompute11.asm /Op /ECSMain
//    BasicCompute11.hlsl
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// Buffer0                           texture    byte         r/o    0        1
// Buffer1                           texture    byte         r/o    1        1
// BufferOut                             UAV    byte         r/w    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_raw t0
dcl_resource_raw t1
dcl_uav_raw u0
dcl_input vThreadID.x
dcl_temps 3
dcl_thread_group 1, 1, 1
ishl r0.x, vThreadID.x, l(3)
ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r0.yz, r0.x, t0.xxyx
ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r1.xy, r0.x, t1.xyxx
iadd r2.x, r0.y, r1.x
add r2.y, r0.z, r1.y
store_raw u0.xy, r0.x, r2.xyxx
ret 
// Approximately 7 instruction slots used
