//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T cs_5_0 /Fo BasicCompute11Double.o /Fc BasicCompute11Double.asm /Op
//    /ECSMain /DTEST_DOUBLE BasicCompute11.hlsl
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// Buffer0                           texture    byte         r/o    0        1
// Buffer1                           texture    byte         r/o    1        1
// BufferOut                             UAV    byte         r/w    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed | enableDoublePrecisionFloatOps
dcl_resource_raw t0
dcl_resource_raw t1
dcl_uav_raw u0
dcl_input vThreadID.x
dcl_temps 4
dcl_thread_group 1, 1, 1
ishl r0.x, vThreadID.x, l(4)
ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r1.xyzw, r0.x, t0.zwxy
ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r2.xyzw, r0.x, t1.zwxy
dadd r3.zw, r1.xyxy, r2.xyxy
iadd r3.x, r1.z, r2.z
add r3.y, r1.w, r2.w
store_raw u0.xyzw, r0.x, r3.xyzw
ret 
// Approximately 8 instruction slots used
