//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// Input                             texture  float4          2d    0        1
// Result                                UAV  float4          2d    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_texture2d (float,float,float,float) t0
dcl_uav_typed_texture2d (float,float,float,float) u0
dcl_input vThreadIDInGroupFlattened
dcl_input vThreadGroupID.xy
dcl_input vThreadID.xy
dcl_temps 3
dcl_tgsm_structured g0, 16, 64
dcl_thread_group 8, 8, 1
mov r0.xy, vThreadID.xyxx
mov r0.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r0.xyzw, r0.xyzw, t0.xyzw
store_structured g0.xyzw, vThreadIDInGroupFlattened.x, l(0), r0.xyzw
sync_g_t
ult r1.xyzw, vThreadIDInGroupFlattened.xxxx, l(32, 16, 8, 4)
if_nz r1.x
  iadd r1.x, vThreadIDInGroupFlattened.x, l(32)
  ld_structured r2.xyzw, r1.x, l(0), g0.xyzw
  add r0.xyzw, r0.xyzw, r2.xyzw
  store_structured g0.xyzw, vThreadIDInGroupFlattened.x, l(0), r0.xyzw
endif 
sync_g_t
if_nz r1.y
  iadd r0.x, vThreadIDInGroupFlattened.x, l(16)
  ld_structured r0.xyzw, r0.x, l(0), g0.xyzw
  ld_structured r2.xyzw, vThreadIDInGroupFlattened.x, l(0), g0.xyzw
  add r0.xyzw, r0.xyzw, r2.xyzw
  store_structured g0.xyzw, vThreadIDInGroupFlattened.x, l(0), r0.xyzw
endif 
sync_g_t
if_nz r1.z
  iadd r0.x, vThreadIDInGroupFlattened.x, l(8)
  ld_structured r0.xyzw, r0.x, l(0), g0.xyzw
  ld_structured r2.xyzw, vThreadIDInGroupFlattened.x, l(0), g0.xyzw
  add r0.xyzw, r0.xyzw, r2.xyzw
  store_structured g0.xyzw, vThreadIDInGroupFlattened.x, l(0), r0.xyzw
endif 
sync_g_t
if_nz r1.w
  iadd r0.x, vThreadIDInGroupFlattened.x, l(4)
  ld_structured r0.xyzw, r0.x, l(0), g0.xyzw
  ld_structured r1.xyzw, vThreadIDInGroupFlattened.x, l(0), g0.xyzw
  add r0.xyzw, r0.xyzw, r1.xyzw
  store_structured g0.xyzw, vThreadIDInGroupFlattened.x, l(0), r0.xyzw
endif 
sync_g_t
ult r0.xy, vThreadIDInGroupFlattened.xxxx, l(2, 1, 0, 0)
if_nz r0.x
  iadd r0.x, vThreadIDInGroupFlattened.x, l(2)
  ld_structured r1.xyzw, r0.x, l(0), g0.xyzw
  ld_structured r2.xyzw, vThreadIDInGroupFlattened.x, l(0), g0.xyzw
  add r1.xyzw, r1.xyzw, r2.xyzw
  store_structured g0.xyzw, vThreadIDInGroupFlattened.x, l(0), r1.xyzw
endif 
sync_g_t
if_nz r0.y
  ld_structured r0.xyzw, l(1), l(0), g0.xyzw
  ld_structured r1.xyzw, l(0), l(0), g0.xyzw
  add r0.xyzw, r0.xyzw, r1.xyzw
  store_structured g0.xyzw, l(0), l(0), r0.xyzw
endif 
if_z vThreadIDInGroupFlattened.x
  ld_structured r0.xyzw, l(0), l(0), g0.xyzw
  mul r0.xyzw, r0.xyzw, l(0.015625, 0.015625, 0.015625, 0.015625)
  store_uav_typed u0.xyzw, vThreadGroupID.xyyy, r0.xyzw
endif 
ret 
// Approximately 58 instruction slots used
