//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// Input                             texture  float4          2d    0        1
// Result                                UAV  float4          2d    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_texture2d (float,float,float,float) t0
dcl_uav_typed_texture2d (float,float,float,float) u0
dcl_input vThreadIDInGroupFlattened
dcl_input vThreadGroupID.xy
dcl_input vThreadID.xy
dcl_temps 3
dcl_tgsm_structured g0, 28, 64
dcl_thread_group 8, 8, 1
mov r0.xy, vThreadID.xyxx
mov r0.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r0.x, r0.xyzw, t0.xyzw
store_structured g0.x, vThreadIDInGroupFlattened.x, l(0), r0.x
add r0.yz, -r0.xxxx, l(0.000000, 1.000000, 0.500000, 0.000000)
store_structured g0.xy, vThreadIDInGroupFlattened.x, l(20), r0.yzyy
sync_g_t
ult r1.xyzw, vThreadIDInGroupFlattened.xxxx, l(32, 16, 8, 4)
if_nz r1.x
  iadd r0.w, vThreadIDInGroupFlattened.x, l(32)
  ld_structured r1.x, r0.w, l(0), g0.xxxx
  ld_structured r2.xy, r0.w, l(20), g0.xyxx
  add r0.x, r0.x, r1.x
  store_structured g0.x, vThreadIDInGroupFlattened.x, l(0), r0.x
  add r0.xy, r0.yzyy, r2.xyxx
  store_structured g0.xy, vThreadIDInGroupFlattened.x, l(20), r0.xyxx
endif 
sync_g_t
if_nz r1.y
  iadd r0.x, vThreadIDInGroupFlattened.x, l(16)
  ld_structured r0.x, r0.x, l(0), g0.xxxx
  ld_structured r0.y, vThreadIDInGroupFlattened.x, l(0), g0.xxxx
  add r0.x, r0.x, r0.y
  store_structured g0.x, vThreadIDInGroupFlattened.x, l(0), r0.x
endif 
sync_g_t
if_nz r1.z
  iadd r0.x, vThreadIDInGroupFlattened.x, l(8)
  ld_structured r0.x, r0.x, l(0), g0.xxxx
  ld_structured r0.y, vThreadIDInGroupFlattened.x, l(0), g0.xxxx
  add r0.x, r0.x, r0.y
  store_structured g0.x, vThreadIDInGroupFlattened.x, l(0), r0.x
endif 
sync_g_t
if_nz r1.w
  iadd r0.x, vThreadIDInGroupFlattened.x, l(4)
  ld_structured r0.x, r0.x, l(0), g0.xxxx
  ld_structured r0.y, vThreadIDInGroupFlattened.x, l(0), g0.xxxx
  add r0.x, r0.x, r0.y
  store_structured g0.x, vThreadIDInGroupFlattened.x, l(0), r0.x
endif 
sync_g_t
ult r0.xy, vThreadIDInGroupFlattened.xxxx, l(2, 1, 0, 0)
if_nz r0.x
  iadd r0.x, vThreadIDInGroupFlattened.x, l(2)
  ld_structured r0.x, r0.x, l(0), g0.xxxx
  ld_structured r0.z, vThreadIDInGroupFlattened.x, l(0), g0.xxxx
  add r0.x, r0.x, r0.z
  store_structured g0.x, vThreadIDInGroupFlattened.x, l(0), r0.x
endif 
sync_g_t
if_nz r0.y
  ld_structured r0.x, l(1), l(0), g0.xxxx
  ld_structured r0.y, l(0), l(0), g0.xxxx
  add r0.x, r0.x, r0.y
  store_structured g0.x, l(0), l(0), r0.x
endif 
if_z vThreadIDInGroupFlattened.x
  ld_structured r0.x, l(0), l(0), g0.xxxx
  ld_structured r0.yz, l(0), l(20), g0.xxyx
  mad r0.x, r0.y, r0.z, r0.x
  mul r0.x, r0.x, l(0.015625)
  store_uav_typed u0.xyzw, vThreadGroupID.xyyy, r0.xxxx
endif 
ret 
// Approximately 65 instruction slots used
