//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Buffer Definitions: 
//
// Resource bind info for g_data
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_data                                UAV  struct         r/w    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_uav_structured u0, 4
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.x
dcl_temps 1
dcl_tgsm_structured g0, 4, 128
dcl_thread_group 128, 1, 1
imad r0.x, vThreadGroupID.x, l(128), vThreadIDInGroup.x
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, r0.x, l(0), u0.xxxx
store_structured g0.x, vThreadIDInGroup.x, l(0), r0.x
sync_g_t
mov r0.x, l(1)
loop 
  uge r0.y, r0.x, l(128)
  breakc_nz r0.y
  ishl r0.y, r0.x, l(1)
  udiv null, r0.z, vThreadIDInGroup.x, r0.y
  if_z r0.z
    iadd r0.z, r0.x, vThreadIDInGroup.x
    ld_structured r0.z, r0.z, l(0), g0.xxxx
    ld_structured r0.w, vThreadIDInGroup.x, l(0), g0.xxxx
    add r0.z, r0.z, r0.w
    store_structured g0.x, vThreadIDInGroup.x, l(0), r0.z
  endif 
  sync_g_t
  mov r0.x, r0.y
endloop 
if_z vThreadIDInGroup.x
  ld_structured r0.x, l(0), l(0), g0.xxxx
  store_structured u0.x, vThreadGroupID.x, l(0), r0.x
endif 
ret 
// Approximately 25 instruction slots used
