//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// OUT_POSITION             0   xyz         0     NONE   float   xyz 
//
gs_5_0
dcl_globalFlags refactoringAllowed
dcl_input v[1][0].xyz
dcl_input v[1][1].xyz
dcl_input vGSInstanceID
dcl_temps 1
dcl_gsinstances 24
dcl_inputprimitive point 
dcl_stream m0
dcl_outputtopology pointlist 
dcl_output o0.xyz
dcl_maxout 18
mul r0.xyz, v[0][0].xyzx, v[0][1].xyzx
utof r0.w, vGSInstanceID.x
mul r0.xyz, r0.wwww, r0.xyzx
mov o0.xyz, r0.xyzx
emit_stream m0
ret 
// Approximately 6 instruction slots used
