//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// m0:OUT_POSITION          0   xyz         0     NONE   float   xyz 
// m1:OUT_POSITION          0   xyz         0     NONE     int   xyz 
//
gs_5_0
dcl_globalFlags refactoringAllowed
dcl_input v[2][0].xyz
dcl_input v[2][1].xyz
dcl_temps 1
dcl_inputprimitive line 
dcl_stream m0
dcl_outputtopology pointlist 
dcl_output o0.xyz
dcl_stream m1
dcl_outputtopology pointlist 
dcl_output o0.xyz
dcl_maxout 18
mul r0.xyz, v[0][0].xyzx, v[0][1].xyzx
mov o0.xyz, r0.xyzx
emit_stream m0
mul r0.xyz, v[1][0].xyzx, v[1][1].xyzx
ftoi r0.xyz, r0.xyzx
mov o0.xyz, r0.xyzx
emit_stream m1
ret 
// Approximately 8 instruction slots used
