//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Buffer Definitions: 
//
// Resource bind info for BufferIncr
// {
//
//   struct MyStruct
//   {
//       
//       uint unused;                   // Offset:    0
//       
//       struct MyStruct::<unnamed>
//       {
//           
//           uint unused2;              // Offset:    4
//
//       } s3;                          // Offset:    4
//
//   } $Element;                        // Offset:    0 Size:     8
//
// }
//
// Resource bind info for BufferDecr
// {
//
//   struct MyStruct2
//   {
//       
//       uint unused;                   // Offset:    0
//
//   } $Element;                        // Offset:    0 Size:     4
//
// }
//
// Resource bind info for app
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for cons
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// BufferIncr                            UAV  struct     r/w+cnt    1        1
// BufferDecr                            UAV  struct     r/w+cnt    2        1
// app                                   UAV  struct      append    3        1
// cons                                  UAV  struct     consume    4        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_uav_structured_opc u1, 8
dcl_uav_structured_opc u2, 4
dcl_uav_structured u3, 4
dcl_uav_structured u4, 4
dcl_output o0.xyzw
dcl_temps 3
imm_atomic_alloc r0.x, u1
imm_atomic_consume r1.x, u2
imm_atomic_alloc r2.x, u3
store_structured u3.x, r2.x, l(0), l(1)
imm_atomic_consume r2.x, u4
utof r0.x, r0.x
mul o0.x, r0.x, l(0.001000)
utof r0.x, r1.x
mul o0.y, r0.x, l(0.001000)
mov o0.zw, l(0,0,1.000000,1.000000)
ret 
// Approximately 11 instruction slots used
