//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T ps_5_0 /Fo conservative_depth_ge.o /Fc conservative_depth_ge.asm
//    /EDepthGreaterThan conservative_depth
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// COLOR                    0   xyzw        0     NONE  float   x   
// DEPTH                    0   x           1     NONE  float   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Target                0   x           0   TARGET  float   x   
// SV_DepthGreaterEqual     0    N/A oDepthGE  DEPTHGE  float    YES
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v0.x
dcl_input_ps linear v1.x
dcl_output o0.x
dcl_output oDepthGE
mov o0.x, v0.x
mov oDepthGE, v1.x
ret 
// Approximately 3 instruction slots used
