//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Buffer Definitions: 
//
// cbuffer cbConstants
// {
//
//   float4x4 g_f4x4WorldViewProjection;// Offset:    0 Size:    64 [unused]
//   float4x4 g_f4x4WorldViewProjLight; // Offset:   64 Size:    64 [unused]
//   float4 g_vShadowMapDimensions;     // Offset:  128 Size:    16
//   float4 g_f4LightDir;               // Offset:  144 Size:    16 [unused]
//   float g_fSunWidth;                 // Offset:  160 Size:     4
//   float3 g_f3Padding;                // Offset:  164 Size:    12 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_SamplePoint                     sampler      NA          NA    0        1
// g_SampleLinear                    sampler      NA          NA    1        1
// g_SamplePointCmp                sampler_c      NA          NA    2        1
// g_txScene                         texture  float4          2d    0        1
// g_txShadowMap                     texture   float          2d    1        1
// cbConstants                       cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXTURE                  0   xy          2     NONE   float   xy  
// TEXTURE                  1   xyzw        3     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_immediateConstantBuffer { { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 1.000000, 0.800000, 0},
                              { 1.000000, 1.000000, 0.800000, 0},
                              { 1.000000, 1.000000, 0.800000, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 1.000000, 0.800000, 0},
                              { 1.000000, 1.000000, 1.000000, 0},
                              { 1.000000, 1.000000, 0.800000, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 1.000000, 0.800000, 0},
                              { 1.000000, 1.000000, 0.800000, 0},
                              { 1.000000, 1.000000, 0.800000, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 1.000000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 1.000000, 0.200000, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0.200000, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0} }
dcl_constantbuffer cb0[11], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_comparison
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xy
dcl_input_ps linear v3.xyzw
dcl_output o0.xyzw
dcl_temps 14
div r0.xyz, v3.xyzx, v3.wwww
mad r1.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
add r0.x, r0.z, l(-0.005000)
add r1.z, -r1.y, l(1.000000)
mad r0.yz, cb0[8].xxyx, r1.xxzx, l(0.000000, 0.500000, 0.500000, 0.000000)
round_ni r1.yw, r0.yyyz
add r0.yz, r0.yyzy, -r1.yywy
mad r1.xy, -r0.yzyy, cb0[8].zwzz, r1.xzxx
mov r1.zw, l(0,0,0,0)
mov r2.y, l(-5)
loop 
  ilt r0.w, l(5), r2.y
  breakc_nz r0.w
  mov r2.zw, r1.zzzw
  mov r2.x, l(-5)
  loop 
    ilt r0.w, l(5), r2.x
    breakc_nz r0.w
    gather4_po_indexable(texture2d)(float,float,float,float) r3.xyzw, r1.xyxx, r2.xyxx, t1.xyzw, s0.x
    ge r4.xyzw, r3.xyzw, r0.xxxx
    movc r4.xyzw, r4.xyzw, l(0,0,0,0), l(1.000000,1.000000,1.000000,1.000000)
    dp4 r0.w, r4.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
    add r2.w, r0.w, r2.w
    dp4 r0.w, r3.xyzw, r4.xyzw
    add r2.z, r0.w, r2.z
    iadd r2.x, r2.x, l(2)
  endloop 
  mov r1.zw, r2.zzzw
  iadd r2.y, r2.y, l(2)
endloop 
lt r0.w, l(0.000000), r1.w
div r1.z, r1.z, r1.w
add r1.w, r0.x, -r1.z
mul r1.w, r1.w, cb0[10].x
div_sat r1.z, r1.w, r1.z
mul r1.z, r1.z, r1.z
and r0.w, r0.w, r1.z
mul r1.z, r0.w, r0.w
mul r1.w, r0.w, r1.z
mul r2.x, r1.z, l(3.000000)
add r2.y, -r0.w, l(1.000000)
mul r2.zw, r2.yyyy, r2.xxxy
mul r3.x, r0.w, r2.w
mul r3.yz, r3.xxxx, l(0.000000, 3.000000, 0.600000, 0.000000)
mul r3.w, r2.y, r2.w
mov r4.xy, l(0,0,0,0)
loop 
  ige r4.z, r4.x, l(11)
  breakc_nz r4.z
  mad r4.z, r1.z, r0.w, r4.y
  imul null, r4.w, r4.x, l(11)
  mad r5.x, r2.z, icb[r4.w + 1].x, r1.w
  add r4.z, r4.z, r5.x
  mad r5.x, r3.y, icb[r4.w + 2].y, r1.w
  mad r5.x, r2.z, icb[r4.w + 2].x, r5.x
  add r4.z, r4.z, r5.x
  mad r5.x, r3.y, icb[r4.w + 3].y, r1.w
  mad r5.x, r2.z, icb[r4.w + 3].x, r5.x
  add r4.z, r4.z, r5.x
  mad r5.x, r3.w, icb[r4.w + 4].z, r1.w
  mad r5.x, r3.y, icb[r4.w + 4].y, r5.x
  mad r5.x, r2.z, icb[r4.w + 4].x, r5.x
  add r4.z, r4.z, r5.x
  mad r5.x, r3.w, icb[r4.w + 5].z, r1.w
  mad r5.x, r3.y, icb[r4.w + 5].y, r5.x
  mad r5.x, r2.z, icb[r4.w + 5].x, r5.x
  add r4.z, r4.z, r5.x
  mad r5.x, r3.w, icb[r4.w + 6].z, r1.w
  mad r5.x, r3.y, icb[r4.w + 6].y, r5.x
  mad r5.x, r2.z, icb[r4.w + 6].x, r5.x
  add r4.z, r4.z, r5.x
  mad r5.x, r3.y, icb[r4.w + 7].y, r1.w
  mad r5.x, r2.z, icb[r4.w + 7].x, r5.x
  add r4.z, r4.z, r5.x
  mad r5.x, r3.y, icb[r4.w + 8].y, r1.w
  mad r5.x, r2.z, icb[r4.w + 8].x, r5.x
  add r4.z, r4.z, r5.x
  mad r4.w, r2.z, icb[r4.w + 9].x, r1.w
  add r4.z, r4.w, r4.z
  mad r4.y, r1.z, r0.w, r4.z
  iadd r4.x, r4.x, l(1)
endloop 
gather4_c_aoffimmi_indexable(-5,-5,0)(texture2d)(float,float,float,float) r5.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
add r4.x, -r0.z, l(1.000000)
mad r4.z, -r1.w, r0.y, r1.w
mul r5.xw, r4.zzzz, r5.wwwx
mad r5.xz, r5.zzyz, r1.wwww, r5.xxwx
mul r4.w, r0.z, r5.z
mad r4.w, r4.x, r5.x, r4.w
gather4_c_aoffimmi_indexable(-3,-5,0)(texture2d)(float,float,float,float) r6.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
dp2 r5.x, r6.wzww, r1.wwww
mad r4.w, r4.x, r5.x, r4.w
dp2 r5.x, r6.xyxx, r1.wwww
mad r4.w, r0.z, r5.x, r4.w
gather4_c_aoffimmi_indexable(-1,-5,0)(texture2d)(float,float,float,float) r7.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
dp2 r5.x, r7.wzww, r1.wwww
mad r4.w, r4.x, r5.x, r4.w
dp2 r5.x, r7.xyxx, r1.wwww
mad r4.w, r0.z, r5.x, r4.w
gather4_c_aoffimmi_indexable(1,-5,0)(texture2d)(float,float,float,float) r8.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
dp2 r5.x, r8.wzww, r1.wwww
mad r4.w, r4.x, r5.x, r4.w
dp2 r5.x, r8.xyxx, r1.wwww
mad r4.w, r0.z, r5.x, r4.w
gather4_c_aoffimmi_indexable(3,-5,0)(texture2d)(float,float,float,float) r9.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
dp2 r5.x, r9.wzww, r1.wwww
mad r4.w, r4.x, r5.x, r4.w
dp2 r5.x, r9.xyxx, r1.wwww
mad r4.w, r0.z, r5.x, r4.w
gather4_c_aoffimmi_indexable(5,-5,0)(texture2d)(float,float,float,float) r10.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r5.xz, r0.yyyy, r10.zzyz
mul r5.xz, r1.wwww, r5.xxzx
mad r6.zw, r10.wwwx, r1.wwww, r5.xxxz
mad r4.w, r4.x, r6.z, r4.w
mad r4.w, r0.z, r6.w, r4.w
gather4_c_aoffimmi_indexable(-5,-3,0)(texture2d)(float,float,float,float) r11.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r2.z, r2.z, l(0.200000)
mad r5.x, r1.z, r0.w, r2.z
mad r6.z, r1.z, r0.w, -r5.x
mad r6.z, r0.y, r6.z, r5.x
mul r7.zw, r6.zzzz, r11.yyyz
mad r7.zw, r11.xxxw, r4.zzzz, r7.zzzw
mad r4.w, r4.x, r7.w, r4.w
mad r4.w, r0.z, r7.z, r4.w
mad r5.y, r5.y, r6.z, r5.w
mad r4.w, r4.x, r5.y, r4.w
mad r4.w, r0.z, r7.w, r4.w
gather4_c_aoffimmi_indexable(-3,-3,0)(texture2d)(float,float,float,float) r11.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mad r3.yz, r1.zzzz, r0.wwww, r3.yyzy
mad r3.yz, r2.xxxx, r2.yyyy, r3.yyzy
add r0.w, -r3.z, r5.x
mad r0.w, r0.y, r0.w, r3.z
mul r5.yw, r0.wwww, r11.wwwx
mad r8.zw, r11.zzzy, r3.zzzz, r5.yyyw
mad r1.z, r4.x, r8.z, r4.w
mad r1.z, r0.z, r8.w, r1.z
dp2 r4.w, r6.xyxx, r5.xxxx
mad r1.z, r4.x, r4.w, r1.z
dp2 r4.w, r11.wzww, r5.xxxx
mad r1.z, r0.z, r4.w, r1.z
gather4_c_aoffimmi_indexable(-1,-3,0)(texture2d)(float,float,float,float) r12.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
dp2 r4.w, r12.wzww, r3.zzzz
mad r1.z, r4.x, r4.w, r1.z
dp2 r4.w, r12.xyxx, r3.zzzz
mad r1.z, r0.z, r4.w, r1.z
dp2 r4.w, r7.xyxx, r5.xxxx
mad r1.z, r4.x, r4.w, r1.z
dp2 r4.w, r12.wzww, r5.xxxx
mad r1.z, r0.z, r4.w, r1.z
gather4_c_aoffimmi_indexable(1,-3,0)(texture2d)(float,float,float,float) r13.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
dp2 r4.w, r13.wzww, r3.zzzz
mad r1.z, r4.x, r4.w, r1.z
dp2 r4.w, r13.xyxx, r3.zzzz
mad r1.z, r0.z, r4.w, r1.z
dp2 r4.w, r8.xyxx, r5.xxxx
mad r1.z, r4.x, r4.w, r1.z
dp2 r4.w, r13.wzww, r5.xxxx
mad r1.z, r0.z, r4.w, r1.z
gather4_c_aoffimmi_indexable(3,-3,0)(texture2d)(float,float,float,float) r8.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
add r4.w, -r5.x, r3.z
mad r4.w, r0.y, r4.w, r5.x
mul r6.xy, r4.wwww, r8.zyzz
mad r6.xw, r8.wwwx, r3.zzzz, r6.xxxy
mad r1.z, r4.x, r6.x, r1.z
mad r1.z, r0.z, r6.w, r1.z
dp2 r5.y, r9.xyxx, r5.xxxx
mad r1.z, r4.x, r5.y, r1.z
dp2 r5.y, r8.wzww, r5.xxxx
mad r1.z, r0.z, r5.y, r1.z
gather4_c_aoffimmi_indexable(5,-3,0)(texture2d)(float,float,float,float) r9.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mad r2.z, r0.y, r2.z, r1.w
mul r6.xw, r0.yyyy, r9.yyyz
mul r6.xw, r1.wwww, r6.xxxw
mad r6.xw, r9.xxxw, r2.zzzz, r6.xxxw
mad r1.z, r4.x, r6.w, r1.z
mad r1.z, r0.z, r6.x, r1.z
mad r5.y, r10.x, r2.z, r5.z
mad r1.z, r4.x, r5.y, r1.z
mad r1.z, r0.z, r6.w, r1.z
gather4_c_aoffimmi_indexable(-5,-1,0)(texture2d)(float,float,float,float) r9.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r5.yz, r6.zzzz, r9.yyzy
mad r5.yz, r9.xxwx, r4.zzzz, r5.yyzy
mad r1.z, r4.x, r5.z, r1.z
mad r1.z, r0.z, r5.y, r1.z
mad r1.z, r4.x, r7.z, r1.z
mad r1.z, r0.z, r5.z, r1.z
gather4_c_aoffimmi_indexable(-3,-1,0)(texture2d)(float,float,float,float) r7.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
add r8.yz, -r3.yyzy, r3.zzyz
mad r8.yz, r0.yyyy, r8.yyzy, r3.yyzy
mul r7.yz, r7.yyzy, r8.yyyy
mad r7.xy, r7.xwxx, r0.wwww, r7.yzyy
mad r1.z, r4.x, r7.y, r1.z
mad r1.z, r0.z, r7.x, r1.z
mad r5.z, r11.y, r8.y, r5.w
mad r1.z, r4.x, r5.z, r1.z
mad r1.z, r0.z, r7.y, r1.z
gather4_c_aoffimmi_indexable(-1,-1,0)(texture2d)(float,float,float,float) r9.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mad r3.w, r3.w, l(0.800000), r1.w
mad r3.w, r3.x, l(3.000000), r3.w
mad r3.w, r2.x, r2.y, r3.w
add r5.z, -r3.w, r3.y
mad r5.z, r0.y, r5.z, r3.w
mul r7.yz, r5.zzzz, r9.wwxw
mad r7.yw, r9.zzzy, r3.wwww, r7.yyyz
mad r1.z, r4.x, r7.y, r1.z
mad r1.z, r0.z, r7.w, r1.z
dp2 r5.w, r12.xyxx, r3.yyyy
mad r1.z, r4.x, r5.w, r1.z
dp2 r5.w, r9.wzww, r3.yyyy
mad r1.z, r0.z, r5.w, r1.z
gather4_c_aoffimmi_indexable(1,-1,0)(texture2d)(float,float,float,float) r10.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
add r5.w, -r3.y, r3.w
mad r5.w, r0.y, r5.w, r3.y
mul r7.yw, r5.wwww, r10.zzzy
mad r9.xz, r10.wwxw, r3.wwww, r7.yywy
mad r1.z, r4.x, r9.x, r1.z
mad r1.z, r0.z, r9.z, r1.z
dp2 r6.w, r13.xyxx, r3.yyyy
mad r1.z, r4.x, r6.w, r1.z
dp2 r6.w, r10.wzww, r3.yyyy
mad r1.z, r0.z, r6.w, r1.z
gather4_c_aoffimmi_indexable(3,-1,0)(texture2d)(float,float,float,float) r11.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r9.xz, r4.wwww, r11.yyzy
mad r9.xz, r11.xxwx, r8.zzzz, r9.xxzx
mad r1.z, r4.x, r9.z, r1.z
mad r1.z, r0.z, r9.x, r1.z
mad r6.y, r8.x, r8.z, r6.y
mad r1.z, r4.x, r6.y, r1.z
mad r1.z, r0.z, r9.z, r1.z
gather4_c_aoffimmi_indexable(5,-1,0)(texture2d)(float,float,float,float) r11.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r6.yw, r0.yyyy, r11.yyyz
mul r6.yw, r1.wwww, r6.yyyw
mad r6.yw, r11.xxxw, r2.zzzz, r6.yyyw
mad r1.z, r4.x, r6.w, r1.z
mad r1.z, r0.z, r6.y, r1.z
mad r1.z, r4.x, r6.x, r1.z
mad r1.z, r0.z, r6.w, r1.z
gather4_c_aoffimmi_indexable(-5,1,0)(texture2d)(float,float,float,float) r11.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r6.xw, r6.zzzz, r11.yyyz
mad r6.xw, r11.xxxw, r4.zzzz, r6.xxxw
mad r1.z, r4.x, r6.w, r1.z
mad r1.z, r0.z, r6.x, r1.z
mad r1.z, r4.x, r5.y, r1.z
mad r1.z, r0.z, r6.w, r1.z
gather4_c_aoffimmi_indexable(-3,1,0)(texture2d)(float,float,float,float) r11.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r8.xw, r8.yyyy, r11.yyyz
mad r8.xw, r11.xxxw, r0.wwww, r8.xxxw
mad r1.z, r4.x, r8.w, r1.z
mad r1.z, r0.z, r8.x, r1.z
mad r1.z, r4.x, r7.x, r1.z
mad r1.z, r0.z, r8.w, r1.z
gather4_c_aoffimmi_indexable(-1,1,0)(texture2d)(float,float,float,float) r11.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r5.yz, r5.zzzz, r11.wwxw
mad r7.xy, r11.zyzz, r3.wwww, r5.yzyy
mad r1.z, r4.x, r7.x, r1.z
mad r1.z, r0.z, r7.y, r1.z
mad r2.w, r2.w, r2.y, r1.w
mad r2.w, r3.x, l(3.000000), r2.w
mad r2.x, r2.x, r2.y, r2.w
add r2.y, -r2.x, r3.w
mad r2.y, r0.y, r2.y, r2.x
mad r2.w, r9.y, r2.y, r7.z
mad r1.z, r4.x, r2.w, r1.z
mad r2.y, r11.z, r2.y, r5.y
mad r1.z, r0.z, r2.y, r1.z
gather4_c_aoffimmi_indexable(1,1,0)(texture2d)(float,float,float,float) r12.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r2.yw, r5.wwww, r12.zzzy
mad r5.yz, r12.wwxw, r3.wwww, r2.yywy
mad r1.z, r4.x, r5.y, r1.z
mad r1.z, r0.z, r5.z, r1.z
add r2.x, -r3.w, r2.x
mad r2.x, r0.y, r2.x, r3.w
mad r2.w, r10.x, r2.x, r7.w
mad r1.z, r4.x, r2.w, r1.z
mad r2.x, r12.w, r2.x, r2.y
mad r1.z, r0.z, r2.x, r1.z
gather4_c_aoffimmi_indexable(3,1,0)(texture2d)(float,float,float,float) r7.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r2.xy, r4.wwww, r7.yzyy
mad r2.xy, r7.xwxx, r8.zzzz, r2.xyxx
mad r1.z, r4.x, r2.y, r1.z
mad r1.z, r0.z, r2.x, r1.z
mad r1.z, r4.x, r9.x, r1.z
mad r1.z, r0.z, r2.y, r1.z
gather4_c_aoffimmi_indexable(5,1,0)(texture2d)(float,float,float,float) r7.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r2.yw, r0.yyyy, r7.yyyz
mul r2.yw, r1.wwww, r2.yyyw
mad r2.yw, r7.xxxw, r2.zzzz, r2.yyyw
mad r1.z, r4.x, r2.w, r1.z
mad r1.z, r0.z, r2.y, r1.z
mad r1.z, r4.x, r6.y, r1.z
mad r1.z, r0.z, r2.w, r1.z
gather4_c_aoffimmi_indexable(-5,3,0)(texture2d)(float,float,float,float) r7.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r3.xw, r6.zzzz, r7.yyyz
mad r3.xw, r7.xxxw, r4.zzzz, r3.xxxw
mad r1.z, r4.x, r3.w, r1.z
mad r1.z, r0.z, r3.x, r1.z
mad r1.z, r4.x, r6.x, r1.z
mad r1.z, r0.z, r3.w, r1.z
gather4_c_aoffimmi_indexable(-3,3,0)(texture2d)(float,float,float,float) r7.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r5.yz, r0.wwww, r7.wwxw
mad r5.zw, r7.zzzy, r3.zzzz, r5.yyyz
mad r0.w, r4.x, r5.z, r1.z
mad r0.w, r0.z, r5.w, r0.w
mad r0.w, r4.x, r8.x, r0.w
mad r1.z, r7.z, r8.y, r5.y
mad r0.w, r0.z, r1.z, r0.w
gather4_c_aoffimmi_indexable(-1,3,0)(texture2d)(float,float,float,float) r9.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
dp2 r1.z, r9.wzww, r3.zzzz
mad r0.w, r4.x, r1.z, r0.w
dp2 r1.z, r9.xyxx, r3.zzzz
mad r0.w, r0.z, r1.z, r0.w
dp2 r1.z, r11.xyxx, r3.yyyy
mad r0.w, r4.x, r1.z, r0.w
dp2 r1.z, r9.wzww, r3.yyyy
mad r0.w, r0.z, r1.z, r0.w
gather4_c_aoffimmi_indexable(1,3,0)(texture2d)(float,float,float,float) r10.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
dp2 r1.z, r10.wzww, r3.zzzz
mad r0.w, r4.x, r1.z, r0.w
dp2 r1.z, r10.xyxx, r3.zzzz
mad r0.w, r0.z, r1.z, r0.w
dp2 r1.z, r12.xyxx, r3.yyyy
mad r0.w, r4.x, r1.z, r0.w
dp2 r1.z, r10.wzww, r3.yyyy
mad r0.w, r0.z, r1.z, r0.w
gather4_c_aoffimmi_indexable(3,3,0)(texture2d)(float,float,float,float) r11.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r3.yw, r4.wwww, r11.zzzy
mad r3.zw, r11.wwwx, r3.zzzz, r3.yyyw
mad r0.w, r4.x, r3.z, r0.w
mad r0.w, r0.z, r3.w, r0.w
mad r0.w, r4.x, r2.x, r0.w
mad r1.z, r11.w, r8.z, r3.y
mad r0.w, r0.z, r1.z, r0.w
gather4_c_aoffimmi_indexable(5,3,0)(texture2d)(float,float,float,float) r8.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r2.xw, r0.yyyy, r8.yyyz
mul r2.xw, r1.wwww, r2.xxxw
mad r2.xw, r8.xxxw, r2.zzzz, r2.xxxw
mad r0.w, r4.x, r2.w, r0.w
mad r0.w, r0.z, r2.x, r0.w
mad r0.w, r4.x, r2.y, r0.w
mad r0.w, r0.z, r2.w, r0.w
gather4_c_aoffimmi_indexable(-5,5,0)(texture2d)(float,float,float,float) r8.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r2.yw, r4.zzzz, r8.wwwx
mad r3.yz, r8.zzyz, r1.wwww, r2.yywy
mad r0.w, r4.x, r3.y, r0.w
mad r0.w, r0.z, r3.z, r0.w
mad r0.w, r4.x, r3.x, r0.w
mad r1.z, r8.z, r6.z, r2.y
mad r0.w, r0.z, r1.z, r0.w
gather4_c_aoffimmi_indexable(-3,5,0)(texture2d)(float,float,float,float) r3.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
dp2 r1.z, r3.wzww, r1.wwww
mad r0.w, r4.x, r1.z, r0.w
dp2 r1.z, r3.xyxx, r1.wwww
mad r0.w, r0.z, r1.z, r0.w
dp2 r1.z, r7.xyxx, r5.xxxx
mad r0.w, r4.x, r1.z, r0.w
dp2 r1.z, r3.wzww, r5.xxxx
mad r0.w, r0.z, r1.z, r0.w
gather4_c_aoffimmi_indexable(-1,5,0)(texture2d)(float,float,float,float) r3.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
dp2 r1.z, r3.wzww, r1.wwww
mad r0.w, r4.x, r1.z, r0.w
dp2 r1.z, r3.xyxx, r1.wwww
mad r0.w, r0.z, r1.z, r0.w
dp2 r1.z, r9.xyxx, r5.xxxx
mad r0.w, r4.x, r1.z, r0.w
dp2 r1.z, r3.wzww, r5.xxxx
mad r0.w, r0.z, r1.z, r0.w
gather4_c_aoffimmi_indexable(1,5,0)(texture2d)(float,float,float,float) r3.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
dp2 r1.z, r3.wzww, r1.wwww
mad r0.w, r4.x, r1.z, r0.w
dp2 r1.z, r3.xyxx, r1.wwww
mad r0.w, r0.z, r1.z, r0.w
dp2 r1.z, r10.xyxx, r5.xxxx
mad r0.w, r4.x, r1.z, r0.w
dp2 r1.z, r3.wzww, r5.xxxx
mad r0.w, r0.z, r1.z, r0.w
gather4_c_aoffimmi_indexable(3,5,0)(texture2d)(float,float,float,float) r3.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
dp2 r1.z, r3.wzww, r1.wwww
mad r0.w, r4.x, r1.z, r0.w
dp2 r1.z, r3.xyxx, r1.wwww
mad r0.w, r0.z, r1.z, r0.w
dp2 r1.z, r11.xyxx, r5.xxxx
mad r0.w, r4.x, r1.z, r0.w
dp2 r1.z, r3.wzww, r5.xxxx
mad r0.w, r0.z, r1.z, r0.w
gather4_c_aoffimmi_indexable(5,5,0)(texture2d)(float,float,float,float) r3.xyzw, r1.xyxx, t1.xyzw, s2.x, r0.x
mul r0.xy, r0.yyyy, r3.zyzz
mul r0.xy, r1.wwww, r0.xyxx
mad r1.xy, r3.wxww, r1.wwww, r0.xyxx
mad r0.y, r4.x, r1.x, r0.w
mad r0.y, r0.z, r1.y, r0.y
mad r0.y, r4.x, r2.x, r0.y
mad r0.x, r3.w, r2.z, r0.x
mad r0.x, r0.z, r0.x, r0.y
div r0.x, r0.x, r4.y
mad_sat r0.xyzw, r0.xxxx, v1.xyzw, l(0.300000, 0.300000, 0.300000, 0.000000)
sample_indexable(texture2d)(float,float,float,float) r1.xyzw, v2.xyxx, t0.xyzw, s1
mul o0.xyzw, r0.xyzw, r1.xyzw
ret 
// Approximately 398 instruction slots used
