//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyzw
// SV_SampleIndex           0   x           1   SAMPLE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Coverage              0    N/A    oMask COVERAGE    uint    YES
//
// Pixel Shader runs at sample frequency
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v0.xyzw
dcl_input_ps_sgv v1.x, sampleIndex
dcl_input vCoverage
dcl_output o0.xyzw
dcl_output oMask
dcl_temps 1
mov o0.xyzw, v0.xyzw
ishl r0.x, l(1), v1.x
and r0.x, r0.x, vCoverage.x
and r0.x, r0.x, l(1)
ine oMask, r0.x, l(0)
ret 
// Approximately 6 instruction slots used
