//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// s                                 sampler      NA          NA    0        1
// Tex2d                             texture    sint          2d    0        1
// Tex2dArray                        texture   sint2     2darray    1        1
// TexCube                           texture   sint3        cube    2        1
// TexCubeArray                      texture  float2   cubearray    3        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET     int   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_sampler s0, mode_default
dcl_resource_texture2d (sint,sint,sint,sint) t0
dcl_resource_texture2darray (sint,sint,sint,sint) t1
dcl_resource_texturecube (sint,sint,sint,sint) t2
dcl_resource_texturecubearray (float,float,float,float) t3
dcl_input_ps_siv linear noperspective v0.xyzw, position
dcl_output o0.xyzw
dcl_temps 2
gather4_indexable(texture2d)(sint,sint,sint,sint) r0.xyzw, v0.xyxx, t0.xyzw, s0.x
gather4_aoffimmi_indexable(2,3,0)(texture2d)(sint,sint,sint,sint) r1.xyzw, v0.xyxx, t0.xyzw, s0.x
iadd r0.xyzw, r0.xyzw, r1.xyzw
gather4_indexable(texture2darray)(sint,sint,sint,sint) r1.xyzw, v0.xyzx, t1.xyzw, s0.x
iadd r0.xyzw, r0.xyzw, r1.xyzw
gather4_aoffimmi_indexable(2,3,0)(texture2darray)(sint,sint,sint,sint) r1.xyzw, v0.xyzx, t1.xyzw, s0.x
iadd r0.xyzw, r0.xyzw, r1.xyzw
gather4_indexable(texturecube)(sint,sint,sint,sint) r1.xyzw, v0.xyzx, t2.xyzw, s0.x
iadd r0.xyzw, r0.xyzw, r1.xyzw
gather4_indexable(texturecubearray)(float,float,float,float) r1.xyzw, v0.xyzw, t3.xyzw, s0.x
ftoi r1.xyzw, r1.xyzw
iadd o0.xyzw, r0.xyzw, r1.xyzw
ret 
// Approximately 13 instruction slots used
