//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Buffer Definitions: 
//
// interfaces $ThisPointer
// {
//
//   interface iChangeColour gAbstractColourChanger;// Offset:    0 Size:     1
//
// }
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyz         0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
//
// Available Class Types:
//
// Name                             ID CB Stride Texture Sampler
// ------------------------------ ---- --------- ------- -------
// cUnchangedColour                  0         0       0       0
// cDoubleColour                     1         0       0       0
//
// Interface slots, 1 total:
//
//             Slots
// +----------+---------+---------------------------------------
// | Type ID  |   0     |0    1    
// | Table ID |         |0    1    
// +----------+---------+---------------------------------------
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_function_body fb0
dcl_function_body fb1
dcl_function_body fb2
dcl_function_body fb3
dcl_function_table ft0 = {fb0, fb2}
dcl_function_table ft1 = {fb1, fb3}
dcl_interface fp0[1][2] = {ft0, ft1}
dcl_input_ps linear v0.xyz
dcl_output o0.xyzw
dcl_temps 1
fcall fp0[0][0]
mov o0.yz, r0.yyzy
fcall fp0[0][1]
mov o0.x, r0.x
mov o0.w, l(1.000000)
ret 
label fb0
mov r0.xyz, v0.xyzx
ret 
label fb1
add r0.xyz, v0.xyzx, v0.xyzx
ret 
label fb2
ret 
label fb3
add r0.x, r0.x, r0.x
ret 
// Approximately 13 instruction slots used
