//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// TextureSampler                    sampler      NA          NA    0        1
// TextureBase                       texture  float4          3d    0        1
// TextureDetail                     texture  float4          3d    1        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_sampler s0, mode_default
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture3d (float,float,float,float) t1
dcl_input_ps linear v0.xyz
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_temps 2
sample_indexable(texture3d)(float,float,float,float) r0.xyzw, v0.xyzx, t0.xyzw, s0
sample_aoffimmi_indexable(1,2,3)(texture3d)(float,float,float,float) r1.xyzw, v0.xyzx, t1.xyzw, s0
mul o0.xyzw, r0.xyzw, r1.xyzw
sample_d_aoffimmi_indexable(4,4,4)(texture3d)(float,float,float,float) r0.xyzw, v0.xyzx, t0.xyzw, s0, l(0.300000, 0.300000, 0.300000, 0.000000), l(0.400000, 0.400000, 0.400000, 0.000000)
sample_d_aoffimmi_indexable(0,3,1)(texture3d)(float,float,float,float) r1.xyzw, v0.xyzx, t1.xyzw, s0, l(0.300000, 0.300000, 0.300000, 0.000000), l(0.400000, 0.400000, 0.400000, 0.000000)
mul o1.xyzw, r0.xyzw, r1.xyzw
sample_b_indexable(texture3d)(float,float,float,float) r0.xyzw, v0.xyzx, t0.xyzw, s0, l(0.200000)
sample_b_aoffimmi_indexable(1,2,-3)(texture3d)(float,float,float,float) r1.xyzw, v0.xyzx, t1.xyzw, s0, l(0.200000)
mul o2.xyzw, r0.xyzw, r1.xyzw
ret 
// Approximately 10 instruction slots used
