//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /T ps_3_0 /Fc constTexCoord.asm /Fo constTexCoord.o constTexCoord
//
//
// Parameters:
//
//   sampler2D Texture0;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   Texture0     s0       1
//

    ps_3_0
    def c0, 0.5, 0, 0, 0
    dcl_2d s0
    texld r0, c0.x, s0
    mov oC0, r0.x

// approximately 2 instruction slots used (1 texture, 1 arithmetic)
