//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
///
// Parameters:
//
//   float4x4 Projection;
//   float4x4 View;
//   float4x4 World;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   World        c0       4
//   View         c4       4
//   Projection   c8       4
//

    vs_2_0
    dcl_position v0
    dcl_normal v1
    dp4 r0.x, v0, c0
    dp4 r0.y, v0, c1
    dp4 r0.z, v0, c2
    dp4 r0.w, v0, c3
    dp4 r1.x, r0, c4
    dp4 r1.y, r0, c5
    dp4 r1.z, r0, c6
    dp4 r1.w, r0, c7
    dp4 oPos.x, r1, c8
    dp4 oPos.y, r1, c9
    dp4 oPos.z, r1, c10
    dp4 oPos.w, r1, c11
    dp3 oT0.x, v1, c0
    dp3 oT0.y, v1, c1
    dp3 oT0.z, v1, c2

// approximately 15 instruction slots used
