//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
///
// Parameters:
//
//   float4 vLightColor[2];
//   float4 vLightDir[2];
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   vLightDir    c12      2
//   vLightColor  c14      2
//

    ps_2_0
    def c0, 1, 0, 0, 0
    dcl t0.xyz
    dp3 r0.w, c12, t0
    mul_sat r0.xyz, r0.w, c14
    dp3 r0.w, c13, t0
    mul_sat r1.xyz, r0.w, c15
    add r0.xyz, r0, r1
    mov r0.w, c0.x
    mov oC0, r0

// approximately 7 instruction slots used
