//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
///
// Parameters:
//
//   float4 vOutputColor;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   vOutputColor c16      1
//

    ps_2_0
    mov oC0, c16

// approximately 1 instruction slot used
