//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T vs_5_0 /Fo tessellationVS.o /Fc tessellationVS.asm /EVS
//    tessellation.hlsl
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   float4x4 MVP;                      // Offset:    0 Size:    64
//   float InnerFactor;                 // Offset:   64 Size:     4 [unused]
//      = 0x3f800000 
//   float OuterFactor;                 // Offset:   68 Size:     4 [unused]
//      = 0x3f800000 
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// $Globals                          cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// CPOINT                   0   xy          0     NONE  float   xy  
// COLOR                    0   xyzw        1     NONE  float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// CPOINT                   0   xyzw        0     NONE  float   xyzw
// COLOR                    0   xyzw        1     NONE  float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[4], immediateIndexed
dcl_input v0.xy
dcl_input v1.xyzw
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 1
mov r0.xy, v0.xyxx
mov r0.z, l(1.000000)
dp3 o0.x, r0.xyzx, cb0[0].xywx
dp3 o0.y, r0.xyzx, cb0[1].xywx
dp3 o0.z, r0.xyzx, cb0[2].xywx
dp3 o0.w, r0.xyzx, cb0[3].xywx
mov o1.xyzw, v1.xyzw
ret 
// Approximately 8 instruction slots used
