//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T hs_5_0 /Fo tessellationHS.o /Fc tessellationHS.asm /EHS
//    tessellation.hlsl
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   float InnerFactor;                 // Offset:    0 Size:     4
//      = 0x3f800000 
//   float OuterFactor;                 // Offset:    4 Size:     4
//      = 0x3f800000 
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// $Globals                          cbuffer      NA          NA    0        1
//
//
//
// Patch Constant signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TessFactor            0   x           0 QUADEDGE  float   x   
// SV_TessFactor            1   x           1 QUADEDGE  float   x   
// SV_TessFactor            2   x           2 QUADEDGE  float   x   
// SV_TessFactor            3   x           3 QUADEDGE  float   x   
// SV_InsideTessFactor      0   x           4  QUADINT  float   x   
// SV_InsideTessFactor      1   x           5  QUADINT  float   x   
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// CPOINT                   0   xyzw        0     NONE  float   xyzw
// COLOR                    0   xyzw        1     NONE  float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// CPOINT                   0   xyzw        0     NONE  float   xyzw
// COLOR                    0   xyzw        1     NONE  float   xyzw
//
// Tessellation Domain   # of control points
// -------------------- --------------------
// Quadrilateral                           4
//
// Tessellation Output Primitive  Partitioning Type 
// ------------------------------ ------------------
// Counter-Clockwise Triangles    Integer           
//
hs_5_0
hs_decls 
dcl_input_control_point_count 4
dcl_output_control_point_count 4
dcl_tessellator_domain domain_quad
dcl_tessellator_partitioning partitioning_integer
dcl_tessellator_output_primitive output_triangle_ccw
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[1], immediateIndexed
hs_fork_phase 
dcl_hs_fork_phase_instance_count 4
dcl_input vForkInstanceID
dcl_output_siv o0.x, finalQuadUeq0EdgeTessFactor
dcl_output_siv o1.x, finalQuadVeq0EdgeTessFactor
dcl_output_siv o2.x, finalQuadUeq1EdgeTessFactor
dcl_output_siv o3.x, finalQuadVeq1EdgeTessFactor
dcl_temps 1
dcl_indexrange o0.x 4
mov r0.x, vForkInstanceID.x
mov o[r0.x + 0].x, cb0[0].y
ret 
hs_fork_phase 
dcl_hs_fork_phase_instance_count 2
dcl_input vForkInstanceID
dcl_output_siv o4.x, finalQuadUInsideTessFactor
dcl_output_siv o5.x, finalQuadVInsideTessFactor
dcl_temps 1
dcl_indexrange o4.x 2
mov r0.x, vForkInstanceID.x
mov o[r0.x + 4].x, cb0[0].x
ret 
// Approximately 6 instruction slots used
