//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T ds_5_0 /Fo tessellationDS.o /Fc tessellationDS.asm /EDS
//    tessellation.hlsl
//
//
//
// Patch Constant signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TessFactor            0   x           0 QUADEDGE  float       
// SV_TessFactor            1   x           1 QUADEDGE  float       
// SV_TessFactor            2   x           2 QUADEDGE  float       
// SV_TessFactor            3   x           3 QUADEDGE  float       
// SV_InsideTessFactor      0   x           4  QUADINT  float       
// SV_InsideTessFactor      1   x           5  QUADINT  float       
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// CPOINT                   0   xyzw        0     NONE  float   xyzw
// COLOR                    0   xyzw        1     NONE  float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Position              0   xyzw        0      POS  float   xyzw
// COLOR                    0   xyzw        1     NONE  float   xyzw
//
// Tessellation Domain   # of control points
// -------------------- --------------------
// Quadrilateral                           4
//
ds_5_0
dcl_input_control_point_count 4
dcl_tessellator_domain domain_quad
dcl_globalFlags refactoringAllowed
dcl_input vDomain.xy
dcl_input vicp[4][0].xyzw
dcl_input vicp[4][1].xyzw
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_temps 2
add r0.xyzw, -vicp[3][0].xyzw, vicp[2][0].xyzw
mad r0.xyzw, vDomain.xxxx, r0.xyzw, vicp[3][0].xyzw
add r1.xyzw, -vicp[0][0].xyzw, vicp[1][0].xyzw
mad r1.xyzw, vDomain.xxxx, r1.xyzw, vicp[0][0].xyzw
add r0.xyzw, r0.xyzw, -r1.xyzw
mad o0.xyzw, vDomain.yyyy, r0.xyzw, r1.xyzw
add r0.xyzw, -vicp[3][1].xyzw, vicp[2][1].xyzw
mad r0.xyzw, vDomain.xxxx, r0.xyzw, vicp[3][1].xyzw
add r1.xyzw, -vicp[0][1].xyzw, vicp[1][1].xyzw
mad r1.xyzw, vDomain.xxxx, r1.xyzw, vicp[0][1].xyzw
add r0.xyzw, r0.xyzw, -r1.xyzw
mad o1.xyzw, vDomain.yyyy, r0.xyzw, r1.xyzw
ret 
// Approximately 13 instruction slots used
