//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Buffer Definitions: 
//
// cbuffer SecondCBuffer
// {
//
//   float4x4 world_view_proj;          // Offset:    0 Size:    64
//
// }
//
// cbuffer FirstCBuffer
// {
//
//   float4 vars;                       // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// FirstCBuffer                      cbuffer      NA          NA    0        1
// SecondCBuffer                     cbuffer      NA          NA    1        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
//
vs_4_0
dcl_constantbuffer cb1[4], immediateIndexed
dcl_constantbuffer cb0[1], immediateIndexed
dcl_input v0.xyzw
dcl_output o0.xyzw
dcl_temps 1
add r0.xyzw, v0.xyzw, cb0[0].xyzw
dp4 o0.x, r0.xyzw, cb1[0].xyzw
dp4 o0.y, r0.xyzw, cb1[1].xyzw
dp4 o0.z, r0.xyzw, cb1[2].xyzw
dp4 o0.w, r0.xyzw, cb1[3].xyzw
ret 
// Approximately 6 instruction slots used
