//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
//
///
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   float4x4 transforms[2];            // Offset:    0 Size:   128
//   int transformsIndex;               // Offset:  128 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// $Globals                          cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
//
vs_4_0
dcl_constantbuffer cb0[9], dynamicIndexed
dcl_input v0.xyzw
dcl_output_siv o0.xyzw, position
dcl_temps 1
ishl r0.x, cb0[8].x, l(2)
dp4 o0.x, v0.xyzw, cb0[r0.x + 0].xyzw
dp4 o0.y, v0.xyzw, cb0[r0.x + 1].xyzw
dp4 o0.z, v0.xyzw, cb0[r0.x + 2].xyzw
dp4 o0.w, v0.xyzw, cb0[r0.x + 3].xyzw
ret 
// Approximately 6 instruction slots used
