//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T vs_4_0 /Fc minmax.asm /Fo minmax.o minmax
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int iValue;                        // Offset:    0 Size:     4
//   float fValue;                      // Offset:    4 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// $Globals                          cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyzw        0     NONE  float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Position              0   xyzw        0      POS  float   xyzw
// INTCLAMP                 0   x           1     NONE    int   x   
// FLOATCLAMP               0   x           2     NONE  float   x   
//
vs_4_0
dcl_constantbuffer cb0[1], immediateIndexed
dcl_input v0.xyzw
dcl_output_siv o0.xyzw, position
dcl_output o1.x
dcl_output o2.x
dcl_temps 1
mov o0.xyzw, v0.xyzw
imin r0.x, cb0[0].x, l(7)
imax o1.x, r0.x, l(1)
min r0.x, cb0[0].y, l(8.100000)
max o2.x, r0.x, l(0.100000)
ret 
// Approximately 6 instruction slots used
