//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T vs_4_0 /Fo switch.o /Fc switch.asm switch
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int SwitchValue;                   // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// $Globals                          cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyzw        0     NONE  float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Position              0   xyzw        0      POS  float   xyzw
// COLOR                    0   xyzw        1     NONE  float   xyzw
//
vs_4_0
dcl_constantbuffer cb0[1], immediateIndexed
dcl_input v0.xyzw
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_temps 1
switch cb0[0].x
  case l(0)
  mov r0.xyzw, l(1.000000,0,0,1.000000)
  break 
  case l(1)
  mov r0.xyzw, l(1.000000,1.000000,0,1.000000)
  break 
  default 
  mov r0.xyzw, l(1.000000,1.000000,1.000000,1.000000)
  break 
endswitch 
mov o1.xyzw, r0.xyzw
mov o0.xyzw, v0.xyzw
ret 
// Approximately 14 instruction slots used
