//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20499
//
///
// Parameters:
//
//   float4 ColOffset;
//   sampler2D g_samScene;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   ColOffset    c0       1
//   g_samScene   s0       1
//

    ps_2_0
    dcl t0.xy
    dcl v0
    dcl_2d s0
    texld r0, t0, s0
    mad r0, r0, v0, c0
    mov oC0, r0

// approximately 3 instruction slots used (1 texture, 2 arithmetic)
