//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /T ps_2_0 /Fc uniformFuncParam.asm /Fo uniformFuncParam.o
//    uniformFuncParam.fx
//
//
// Parameters:
//
//   sampler2D $diffuseMap;
//   float4 $diffuseMaterialColor;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   $diffuseMaterialColor c0       1
//   $diffuseMap           s0       1
//

    ps_2_0
    dcl t0.xy
    dcl_2d s0
    texld r0, t0, s0
    mul r0, r0, c0
    mov oC0, r0

// approximately 3 instruction slots used (1 texture, 2 arithmetic)
